---

- name: Copy the my.cnf file
  ansible.builtin.template:
    mode: "0644"
    src: "my.cnf.j2"
    dest: "{{ mysql_conf_dir }}/mysql.conf.d/mysqld.cnf"
  notify:
    - restart mysql


- name: Deploy mysql config to conf.d
  ansible.builtin.template:
    mode: "0644"
    src: mysql.cnf.j2
    dest: "{{ mysql_conf_dir }}/conf.d/mysql.cnf"
  notify:
    - restart mysql

- name: Start the mysql services
  ansible.builtin.service:
    name: Mysql
    state: started
    enabled: true

- name: Update mysql root password for all root accounts
  mysql_user:
    name: Root
    host: "{{ item }}"
    password: "{{ mysql_root_db_pass }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: ansible_hostname != 'localhost'

- name: Update mysql root password for all root accounts
  mysql_user:
    name: Root
    host: "{{ item }}"
    password: "{{ mysql_root_db_pass }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  when: ansible_hostname == 'localhost'

- name: Copy .my.cnf file with root password credentials
  ansible.builtin.template:
    src: ".my.cnf.j2"
    dest: "~/.my.cnf"
    mode: 0600
