---

- name: Setup group
  ansible.builtin.group:
    name: "{{ mysql_group }}"
    system: true

- name: Setup user
  ansible.builtin.user:
    name: "{{ mysql_user }}"
    system: true
    createhome: false
    group: "{{ mysql_group }}"
