---

- name: Restart mysql
  ansible.builtin.service:
    name: Mysql
    state: restarted
    enabled: true
- name: Reload mysql
  ansible.builtin.service:
    name: Mysql
    state: reloaded
    enabled: true
- name: Start mysql
  ansible.builtin.service:
    name: Mysql
    state: started
    enabled: true
